Revert "package/dtc: bump to v1.5.1"
This reverts commit 1e55b66e975d234f5bff992785762e8f7ee5f5b9.

This bump breaks the build of a number of defconfigs with errors like:

HOSTCC  scripts/dtc/libfdt/fdt_ro.o
scripts/dtc/libfdt/fdt_ro.c:92:10: error: redefinition of ‘fdt_get_max_phandle’
uint32_t fdt_get_max_phandle(const void *fdt)
^~~~~~~~~~~~~~~~~~~
In file included from scripts/dtc/libfdt/fdt_ro.c:54:
/work/beaglebone/host/include/libfdt.h:384:24: note: previous definition of ‘fdt_get_max_phandle’ was here

So revert it for 2019.11.

Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
(cherry picked from commit b78eecb2c2a97742cf5cb7e526dffe01d881e753)
Signed-off-by: Stewart Smith <stewart@flamingspork.com>